package mainGUI;

import util.SortReferences;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Flávio Barreiro Landes 
 * E-mail: landesflavio@gmail.com
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnSort.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSort.setText("Ordenar!");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(btnSort)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        String text = this.jTextArea1.getText();
        int begin;
        ArrayList<String> textRow = new ArrayList<String>();
        String row;
        SortReferences comparator = new SortReferences();
        int index;

        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo de referências está vazio!");
        } else {

            // Delete the first character if it is == '\n'.
            while (text.charAt(0) == '\n') {
                if (text.length() > 1) {
                    text = text.substring(1, text.length());
                } else {
                    text = "";
                    this.jTextArea1.setText("");
                    JOptionPane.showMessageDialog(null, "Campo de referências está vazio!");
                    break;
                }
            }

            if (text.isEmpty() == false) {

                // Delete the last character if it is == '\n'.
                while (text.charAt(text.length() - 1) == '\n') {
                    text = text.substring(0, text.length() - 1);
                }

                // Delete the middle character case it is == '\n'.
                index = 0;
                while (index < text.length() - 1) {
                    if (text.charAt(index) == '\n' && text.charAt(index + 1) == '\n') {
                        text = text.substring(0, index) + text.substring(index + 1, text.length());
                    } else {
                        index++;
                    }
                }

                // Add text within of the raw to an ArrayList.
                begin = 0;
                for (int end = 0; end < text.length(); end++) {
                    if (text.charAt(end) == '\n' || end == text.length() - 1) {
                        if (text.charAt(end) == '\n') {
                            row = text.substring(begin, end);
                            textRow.add(row);
                            begin = end + 1;
                        } else {
                            row = text.substring(begin, end + 1);
                            textRow.add(row);
                        }
                    }
                }

                // Sorting 
                textRow.sort(comparator);

                // Add elements in the GUI
                this.jTextArea1.setText("");
                for (int count = 0; count < textRow.size(); count++) {
                    row = textRow.get(count);
                    this.jTextArea1.append(row + "\n");
                }

                JOptionPane.showMessageDialog(null, "Referências ordenadas com sucesso!");
            }
        }
    }//GEN-LAST:event_btnSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
